TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Swisscom.Neos.ElasticSearch': TRUE
Flowpack:
  ElasticSearch:
    clients:
      default:
        -
          host: 'elasticsearch'
          port: 9200